### ISSUE TITLE
Clicking outside or pressing Esc on Dialog does not close Alert Dialog

### ISSUE THREAD

**Issue by TGlide** [WailAbou/shadcn-svelte-nodep#10]
[WAI-ARIA Dialog Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/)

**Comment by WailAbou** [comment]
@TGlide I believe you meant that clicking outside of the Alert Dialog should close it, but this behavior should be exclusive to the Dialog, or am I mistaken?

The escape button should be fixed with this new [PR](https://github.com/WailAbou/shadcn-svelte-nodep/pull/15).

**Comment by TGlide** [comment]
> @TGlide I believe you meant that clicking outside of the Alert Dialog should close it, but this behavior should be exclusive to the Dialog, or am I mistaken?
> 
> The escape button should be fixed with this new [PR](https://github.com/WailAbou/shadcn-svelte-nodep/pull/15).

Forgive me, you're correct!
