### ISSUE TITLE
Amazing work

### ISSUE THREAD

**Issue by akshay6893** [WailAbou/shadcn-svelte-nodep#52]
Hey there,
I am using your lib in my project and having a great time.
Simple. Pure html and js.
It's been a huge help in my work, and I appreciate your dedication and responsiveness.
Keep up the great work.
Cheers.

**Comment by WailAbou** [comment]
Hi there,

Thank you so much for your kind words! It’s incredibly motivating to hear that the library is helping you in your project.

If there’s anything specific you’d like to see added or improved, please let me know. Right now, I’m working on the input OTP component, which I hope to finish soon :)

Cheers!

**Comment by akshay6893** [comment]
No man, just go with your pace and Just wanted to let you know that your work is really good :)
